[package]
name = "rendering-experiment"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"

[dependencies]
image = "0.22.4"
indicatif = "0.13.0"
nalgebra-glm = "0.5.0"
stl_io = "0.4.2"
